<Project Sdk="Microsoft.NET.Sdk.Razor">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<GenerateDocumentationFile>true</GenerateDocumentationFile>
		<AssemblyName>addons</AssemblyName>
		<PackageId>addons</PackageId>
		<LangVersion>14</LangVersion>
		<NoWarn>1701;1702;1591;</NoWarn>
		<WarningsAsErrors></WarningsAsErrors>
		<TreatWarningsAsErrors>False</TreatWarningsAsErrors>
		<AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
		<DefineConstants>SANDBOX</DefineConstants>
		<AllowUnsafeBlocks>False</AllowUnsafeBlocks>
		<SboxDir Condition="'$(SboxDir)' == ''">$(SBOX_DIR)</SboxDir>
		<OutputPath Condition="'$(SboxDir)' != ''">$(SboxDir)/.vs/output/</OutputPath>
		<OutputPath Condition="'$(SboxDir)' == ''">bin/</OutputPath>
		<DocumentationFile Condition="'$(SboxDir)' != ''">$(SboxDir)/.vs/output/addons.xml</DocumentationFile>
		<DocumentationFile Condition="'$(SboxDir)' == ''">bin/addons.xml</DocumentationFile>
		<RootNamespace>Sandbox</RootNamespace>
		<Nullable>disable</Nullable>
	</PropertyGroup>

	<ItemGroup>
		<Using Include="Sandbox.Internal.GlobalGameNamespace" Static="true" />
		<Using Include="Microsoft.AspNetCore.Components" />
		<Using Include="Microsoft.AspNetCore.Components.Rendering" />
	</ItemGroup>

	<ItemGroup Condition="'$(SboxDir)' != ''">
		<Analyzer Include="$(SboxDir)/bin/managed/Sandbox.CodeUpgrader.dll"/> 
		<Analyzer Include="$(SboxDir)/bin/managed/Sandbox.Generator.dll"/> 
		<Reference Include="$(SboxDir)/bin/managed/Sandbox.System.dll"/> 
		<Reference Include="$(SboxDir)/bin/managed/Sandbox.Engine.dll"/> 
		<Reference Include="$(SboxDir)/bin/managed/Sandbox.Filesystem.dll"/> 
		<Reference Include="$(SboxDir)/bin/managed/Sandbox.Reflection.dll"/> 
		<Reference Include="$(SboxDir)/bin/managed/Sandbox.Mounting.dll"/> 
		<Reference Include="$(SboxDir)/bin/managed/Microsoft.AspNetCore.Components.dll"/> 
	</ItemGroup>

	<ItemGroup Condition="'$(SboxDir)' != ''">
		<ProjectReference Include="$(SboxDir)/addons/base/code/Base Library.csproj" />
	</ItemGroup>

</Project>
