<#
.SYNOPSIS
  Ensure dxrp/game/Code/rp.csproj exists for dxrp-server.cs verifyAddons builds.

.DESCRIPTION
  Dxura's launcher runs `dotnet build game/Code/rp.csproj`. That file is gitignored
  (generated by s&box locally) and is not in the dxrp git clone — verifyAddons then
  fails at [5/7] with MSB1009. This writes a csproj pointing at the staging s&box
  managed assemblies. The file survives dxrp-server git reset (gitignored).
#>
[CmdletBinding()]
param(
    [string] $InstallRoot = 'C:\SBOX-DXRP-Server',
    [string] $SboxRoot = '',
    [string] $RepoDir = ''
)

$ErrorActionPreference = 'Stop'

if (-not $SboxRoot) {
    if (Test-Path -LiteralPath (Join-Path $InstallRoot 'bin\managed\Sandbox.Engine.dll')) {
        $SboxRoot = $InstallRoot
    }
    else {
        $SboxRoot = 'C:\Program Files (x86)\Steam\steamapps\common\sbox'
    }
}

if (-not $RepoDir) {
    $RepoDir = Join-Path $InstallRoot 'dxrp'
}

$codeDir = Join-Path $RepoDir 'game\Code'
$csproj = Join-Path $codeDir 'rp.csproj'

if (-not (Test-Path -LiteralPath (Join-Path $RepoDir 'game'))) {
    Write-Host ('Skip rp.csproj — dxrp repo not cloned yet at ' + $RepoDir) -ForegroundColor DarkGray
    return
}

New-Item -ItemType Directory -Force -Path $codeDir | Out-Null

$sbox = ($SboxRoot -replace '\\', '/').TrimEnd('/')
$out = ((Join-Path $InstallRoot '.vs\output') -replace '\\', '/')
$managed = "$sbox/bin/managed"

foreach ($p in @("$managed/Sandbox.System.dll", "$managed/Sandbox.Engine.dll")) {
    $native = $p -replace '/', '\'
    if (-not (Test-Path -LiteralPath $native)) {
        throw "Missing s&box path for rp.csproj: $native"
    }
}

$baseLibPath = "$sbox/addons/base/code/Base Library.csproj"
$baseLibNative = $baseLibPath -replace '/', '\'
$includeBaseLib = Test-Path -LiteralPath $baseLibNative

$content = @"
<Project Sdk="Microsoft.NET.Sdk.Razor">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<GenerateDocumentationFile>true</GenerateDocumentationFile>
		<AssemblyName>rp</AssemblyName>
		<PackageId>rp</PackageId>
		<LangVersion>14</LangVersion>
		<NoWarn>1701;1702;1591;</NoWarn>
		<WarningsAsErrors></WarningsAsErrors>
		<TreatWarningsAsErrors>False</TreatWarningsAsErrors>
		<AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
		<DefineConstants>SANDBOX;ADDON;DEBUG</DefineConstants>
		<AllowUnsafeBlocks>False</AllowUnsafeBlocks>
		<OutputPath>$out/</OutputPath>
		<DocumentationFile>$out/rp.xml</DocumentationFile>
		<RootNamespace>Dxura.RP.Game</RootNamespace>
		<Nullable>enable</Nullable>
		<DefaultItemExcludes>`$(DefaultItemExcludes);**/editor/**;**/unittest/**</DefaultItemExcludes>
	</PropertyGroup>

	<ItemGroup>
		<Using Include="Sandbox.Internal.GlobalGameNamespace" Static="true" />
		<Using Include="Microsoft.AspNetCore.Components" />
		<Using Include="Microsoft.AspNetCore.Components.Rendering" />
	</ItemGroup>

	<ItemGroup>
		<Analyzer Include="$managed/Sandbox.CodeUpgrader.dll"/>
		<Analyzer Include="$managed/Sandbox.Generator.dll"/>
		<Reference Include="$managed/Sandbox.System.dll"/>
		<Reference Include="$managed/Sandbox.Engine.dll"/>
		<Reference Include="$managed/Sandbox.Filesystem.dll"/>
		<Reference Include="$managed/Sandbox.Reflection.dll"/>
		<Reference Include="$managed/Sandbox.Mounting.dll"/>
		<Reference Include="$managed/Microsoft.AspNetCore.Components.dll"/>
	</ItemGroup>
$(if ($includeBaseLib) {
@"
	<ItemGroup>
		<ProjectReference Include="$baseLibPath" />
	</ItemGroup>
"@
})
</Project>
"@

Set-Content -LiteralPath $csproj -Value $content -Encoding UTF8
Write-Host ('Ensured rp.csproj -> ' + $csproj) -ForegroundColor DarkGray
